GET http://localhost:8080/ping

### register patient
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "email": "patient@example.com",
    "password": "securepassword123",
    "role": "patient"
}

### register doctor
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "email": "doctor@example.com",
    "password": "securepassword123",
    "role": "doctor",
    "specialization": "Cardiology"
}

### Login patient
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "patient@example.com",
    "password": "securepassword123",
    "role": "patient"
}

### Logindoctor
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "doctor@example.com",
    "password": "securepassword123",
    "role": "doctor"
}

### Refresh Token
POST http://localhost:8080/auth/refresh
Content-Type: application/json

{}

### Logout
POST http://localhost:8080/auth/logout
Content-Type: application/json

{}

### Get Me
GET http://localhost:8080/api/me
Content-Type: application/json

### Get patient appointments
GET http://localhost:8080/api/patient/appointments
Content-Type: application/json

### Get doctor schedule
GET http://localhost:8080/api/doctor/schedule
Content-Type: application/json

### Complete Patient Profile
POST http://localhost:8080/api/patient/profile
Content-Type: application/json

{
    "first_name": "Jan",
    "last_name": "Kowalski",
    "pesel": "90010112345"
}

### Complete Doctor Profile
POST http://localhost:8080/api/doctor/profile
Content-Type: application/json

{
    "first_name": "Anna",
    "last_name": "Nowak",
    "specialization": "Kardiologia",
    "examination_ids": [1, 2, 6]
}

### Get patient profile
GET http://localhost:8080/api/patient/profile

### Get doctor profile
GET http://localhost:8080/api/doctor/profile

### Get examinations
GET http://localhost:8080/api/examinations